/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/casinos/{casino_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get casino details
         * @description Returns foundational casino metadata for the given identifier.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    casino_id: components["parameters"]["CasinoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Casino found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Casino"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/casinos/{casino_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update casino settings
         * @description Mutates timezone and policy thresholds for a casino. Requires Idempotency-Key.
         */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    casino_id: components["parameters"]["CasinoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CasinoSettingsPatch"];
                };
            };
            responses: {
                /** @description Settings updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["CasinoSettings"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
            };
        };
        trace?: never;
    };
    "/casinos/{casino_id}/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List casino staff
         * @description Paginates staff records for a casino with optional role/status filtering.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: components["schemas"]["StaffStatus"];
                    role?: components["schemas"]["StaffRole"];
                };
                header?: never;
                path: {
                    casino_id: components["parameters"]["CasinoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Staff page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["StaffList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List players */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    q?: string;
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["PlayerList"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create player */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlayerCreate"];
                };
            };
            responses: {
                /** @description Player created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Player"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    player_id: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Player detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Player"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update player */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    player_id: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlayerUpdate"];
                };
            };
            responses: {
                /** @description Player updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Player"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visits */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    player_id?: components["schemas"]["UUID"];
                    status?: components["schemas"]["VisitStatus"];
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visit list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["VisitList"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Start visit */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VisitStart"];
                };
            };
            responses: {
                /** @description Visit started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Visit"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get visit */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    visit_id: components["parameters"]["VisitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Visit detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Visit"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close visit */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    visit_id: components["parameters"]["VisitId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VisitEnd"];
                };
            };
            responses: {
                /** @description Visit closed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Visit"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{visit_id}/rating-slips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rating slips for a visit */
        get: {
            parameters: {
                query?: {
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    visit_id: components["parameters"]["VisitId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rating slips for visit */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["RatingSlipList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating-slips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create rating slip */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RatingSlipCreate"];
                };
            };
            responses: {
                /** @description Rating slip created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["RatingSlip"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rating-slips/{rating_slip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update rating slip */
        patch: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    rating_slip_id: components["parameters"]["RatingSlipId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RatingSlipUpdate"];
                };
            };
            responses: {
                /** @description Rating slip updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["RatingSlip"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/rating-slips/{rating_slip_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close rating slip */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    rating_slip_id: components["parameters"]["RatingSlipId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RatingSlipClose"];
                };
            };
            responses: {
                /** @description Rating slip closed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["RatingSlip"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table-context/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tables */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    status?: components["schemas"]["TableStatus"];
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tables */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["TableList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table-context/tables/{table_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get table */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    table_id: components["parameters"]["TableId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Table detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["Table"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/table-context/dealer-rotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start dealer rotation */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DealerRotationCreate"];
                };
            };
            responses: {
                /** @description Rotation started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["DealerRotation"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loyalty/mid-session-reward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue mid-session reward */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MidSessionReward"];
                };
            };
            responses: {
                /** @description Reward issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["MidSessionRewardResult"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loyalty/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get player loyalty balance */
        get: {
            parameters: {
                query: {
                    player_id: components["schemas"]["UUID"];
                    casino_id: components["schemas"]["UUID"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Loyalty balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["LoyaltyBalance"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loyalty/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List loyalty ledger entries */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    player_id?: components["schemas"]["UUID"];
                    rating_slip_id?: components["schemas"]["UUID"];
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Loyalty ledger entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["LoyaltyLedgerList"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List financial transactions */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    player_id?: components["schemas"]["UUID"];
                    gaming_day?: string;
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["FinancialTransactionList"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create financial transaction */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FinancialTransactionCreate"];
                };
            };
            responses: {
                /** @description Transaction recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["FinancialTransactionCreated"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/finance/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get financial transaction */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    transaction_id: components["parameters"]["TransactionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transaction detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["FinancialTransaction"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mtl/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List MTL entries */
        get: {
            parameters: {
                query: {
                    casino_id: components["schemas"]["UUID"];
                    patron_uuid?: components["schemas"]["UUID"];
                    min_amount?: number;
                    /** @description Base64 cursor token from previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entry list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["MtlEntryList"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create MTL entry */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MtlEntryCreate"];
                };
            };
            responses: {
                /** @description Entry recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["MtlEntry"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mtl/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get MTL entry */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entry_id: components["parameters"]["MtlEntryId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entry detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["MtlEntry"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mtl/entries/{entry_id}/audit-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append MTL audit note */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Unique key per mutating request to guarantee idempotency. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    entry_id: components["parameters"]["MtlEntryId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MtlAuditNoteCreate"];
                };
            };
            responses: {
                /** @description Audit note appended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                            data?: components["schemas"]["MtlAuditNote"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ServiceHttpResultBase: {
            ok: boolean;
            /** @enum {string} */
            code: "OK" | "VALIDATION_ERROR" | "NOT_FOUND" | "UNIQUE_VIOLATION" | "FOREIGN_KEY_VIOLATION" | "UNAUTHORIZED" | "FORBIDDEN" | "INTERNAL_ERROR";
            status: number;
            requestId: string;
            durationMs: number;
            /** Format: date-time */
            timestamp: string;
            error?: string | null;
            /** @description Additional structured error context. */
            details?: unknown;
        };
        /** Format: uuid */
        UUID: string;
        Casino: {
            id?: components["schemas"]["UUID"];
            name?: string;
            location?: string | null;
            status?: string;
            address?: {
                [key: string]: unknown;
            } | null;
            company_id?: components["schemas"]["UUID"];
            created_at?: string;
        };
        CasinoSettings: {
            casino_id?: components["schemas"]["UUID"];
            timezone?: string;
            gaming_day_start_time?: string;
            watchlist_floor?: number;
            ctr_threshold?: number;
            updated_at?: string;
        };
        CasinoSettingsPatch: {
            timezone?: string;
            gaming_day_start_time?: string;
            watchlist_floor?: number;
            ctr_threshold?: number;
        };
        /** @enum {string} */
        StaffRole: "dealer" | "pit_boss" | "admin";
        /** @enum {string} */
        StaffStatus: "active" | "inactive";
        Staff: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string | null;
            employee_id?: string | null;
            role?: components["schemas"]["StaffRole"];
            status?: components["schemas"]["StaffStatus"];
            created_at?: string;
        };
        StaffList: {
            items?: components["schemas"]["Staff"][];
            next_cursor?: string | null;
        };
        Player: {
            id?: components["schemas"]["UUID"];
            first_name?: string;
            last_name?: string;
            birth_date?: string | null;
            created_at?: string;
        };
        PlayerCreate: {
            first_name: string;
            last_name: string;
            birth_date?: string;
            casino_enrollment?: {
                casino_id: components["schemas"]["UUID"];
                /** @enum {string} */
                status?: "active" | "inactive";
            };
        };
        /** @description Partial updates allowed; at least one field required. */
        PlayerUpdate: components["schemas"]["PlayerCreate"];
        PlayerList: {
            items?: components["schemas"]["Player"][];
            next_cursor?: string | null;
        };
        Visit: {
            id?: components["schemas"]["UUID"];
            player_id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            started_at?: string;
            ended_at?: string | null;
        };
        VisitStart: {
            player_id: components["schemas"]["UUID"];
            casino_id: components["schemas"]["UUID"];
            started_at?: string;
        };
        VisitEnd: {
            ended_at?: string;
        };
        VisitList: {
            items?: components["schemas"]["Visit"][];
            next_cursor?: string | null;
        };
        /** @enum {string} */
        VisitStatus: "open" | "closed";
        RatingSlip: {
            id?: components["schemas"]["UUID"];
            player_id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            table_id?: components["schemas"]["UUID"];
            game_settings?: {
                [key: string]: unknown;
            } | null;
            average_bet?: number | null;
            start_time?: string;
            end_time?: string | null;
            /** @enum {string} */
            status?: "open" | "paused" | "closed";
            policy_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        RatingSlipCreate: {
            player_id: components["schemas"]["UUID"];
            casino_id: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            table_id?: components["schemas"]["UUID"];
            game_settings?: {
                [key: string]: unknown;
            } | null;
            average_bet?: number | null;
            policy_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        RatingSlipUpdate: {
            average_bet?: number | null;
            end_time?: string;
            /** @enum {string} */
            status?: "open" | "paused" | "closed";
            policy_snapshot?: {
                [key: string]: unknown;
            } | null;
        };
        RatingSlipClose: {
            end_time?: string;
        };
        RatingSlipList: {
            items?: components["schemas"]["RatingSlip"][];
            next_cursor?: string | null;
        };
        Table: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            label?: string;
            pit?: string | null;
            type?: components["schemas"]["GameType"];
            status?: components["schemas"]["TableStatus"];
            created_at?: string;
        };
        TableList: {
            items?: components["schemas"]["Table"][];
            next_cursor?: string | null;
        };
        /** @enum {string} */
        GameType: "blackjack" | "poker" | "roulette" | "baccarat";
        /** @enum {string} */
        TableStatus: "inactive" | "active" | "closed";
        DealerRotation: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            table_id?: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            started_at?: string;
            ended_at?: string | null;
        };
        DealerRotationCreate: {
            casino_id: components["schemas"]["UUID"];
            table_id: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            started_at?: string;
        };
        MidSessionReward: {
            casino_id: components["schemas"]["UUID"];
            player_id: components["schemas"]["UUID"];
            rating_slip_id: components["schemas"]["UUID"];
            staff_id: components["schemas"]["UUID"];
            points: number;
            reason?: components["schemas"]["LoyaltyReason"];
            idempotency_key?: string;
        };
        MidSessionRewardResult: {
            ledger_id?: components["schemas"]["UUID"];
            balance_after?: number;
        };
        /** @enum {string} */
        LoyaltyReason: "mid_session" | "session_end" | "manual_adjustment" | "promotion" | "correction";
        LoyaltyBalance: {
            player_id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            balance?: number;
            tier?: string | null;
            preferences?: {
                [key: string]: unknown;
            };
            updated_at?: string;
        };
        LoyaltyLedgerEntry: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            player_id?: components["schemas"]["UUID"];
            rating_slip_id?: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            points_earned?: number;
            reason?: components["schemas"]["LoyaltyReason"];
            idempotency_key?: string | null;
            average_bet?: number | null;
            duration_seconds?: number | null;
            game_type?: components["schemas"]["GameType"];
            created_at?: string;
        };
        LoyaltyLedgerList: {
            items?: components["schemas"]["LoyaltyLedgerEntry"][];
            next_cursor?: string | null;
        };
        FinancialTransactionCreate: {
            casino_id: components["schemas"]["UUID"];
            player_id: components["schemas"]["UUID"];
            amount: number;
            tender_type?: string;
            created_at?: string;
            visit_id?: components["schemas"]["UUID"];
            rating_slip_id?: components["schemas"]["UUID"];
        };
        FinancialTransactionCreated: {
            id?: components["schemas"]["UUID"];
        };
        FinancialTransaction: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            player_id?: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            rating_slip_id?: components["schemas"]["UUID"];
            amount?: number;
            tender_type?: string | null;
            created_at?: string;
            gaming_day?: string | null;
        };
        FinancialTransactionList: {
            items?: components["schemas"]["FinancialTransaction"][];
            next_cursor?: string | null;
        };
        MtlEntryCreate: {
            casino_id: components["schemas"]["UUID"];
            patron_uuid: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            rating_slip_id?: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            amount: number;
            direction: components["schemas"]["MtlDirection"];
            area?: string;
            idempotency_key?: string;
            created_at?: string;
        };
        /** @enum {string} */
        MtlDirection: "in" | "out";
        MtlEntry: {
            id?: components["schemas"]["UUID"];
            casino_id?: components["schemas"]["UUID"];
            patron_uuid?: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            rating_slip_id?: components["schemas"]["UUID"];
            visit_id?: components["schemas"]["UUID"];
            amount?: number;
            direction?: components["schemas"]["MtlDirection"];
            area?: string | null;
            created_at?: string;
            idempotency_key?: string | null;
        };
        MtlEntryList: {
            items?: components["schemas"]["MtlEntry"][];
            next_cursor?: string | null;
        };
        MtlAuditNoteCreate: {
            staff_id: components["schemas"]["UUID"];
            note: string;
        };
        MtlAuditNote: {
            id?: components["schemas"]["UUID"];
            mtl_entry_id?: components["schemas"]["UUID"];
            staff_id?: components["schemas"]["UUID"];
            note?: string;
            created_at?: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                    data?: unknown;
                    /** @example Record not found */
                    error?: unknown;
                    /** @enum {unknown} */
                    code?: "NOT_FOUND";
                };
            };
        };
        /** @description Validation failed */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ServiceHttpResultBase"] & {
                    /** @enum {unknown} */
                    code?: "VALIDATION_ERROR";
                };
            };
        };
    };
    parameters: {
        CasinoId: components["schemas"]["UUID"];
        PlayerId: components["schemas"]["UUID"];
        VisitId: components["schemas"]["UUID"];
        RatingSlipId: components["schemas"]["UUID"];
        TableId: components["schemas"]["UUID"];
        TransactionId: components["schemas"]["UUID"];
        MtlEntryId: components["schemas"]["UUID"];
        /** @description Unique key per mutating request to guarantee idempotency. */
        IdempotencyKey: string;
        /** @description Base64 cursor token from previous page. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
