#!/bin/sh
# ==============================================================================
# Migration Safety Check - RLS Policy Protection
# ==============================================================================
# Version: 4.1.0
# Date: 2026-05-18
# References:
#   - ADR-024: Authoritative context derivation (set_rls_context_from_staff)
#   - ADR-030: Auth pipeline hardening
#   - SEC-007: Tenant isolation enforcement
#   - ADR-015: RLS Connection Pooling Strategy (Hybrid Pattern C)
#   - SEC-001: Casino-Scoped RLS Policy Matrix (Pattern C)
#   - SEC-002: Casino-Scoped Security Model (Context Injection)
#   - ISSUE-002: sync_remote_changes.sql overwrote ADR-015 hybrid RLS policies
#
# Prevents accidental RLS policy regressions from:
#   1. Supabase CLI auto-generated sync_remote_changes.sql files
#   2. Migrations that modify RLS policies without explicit review markers
#   3. Policy changes that may lack ADR-015 hybrid fallback pattern
#   4. Missing context injection (set_rls_context_from_staff)
#
# Post-SEC-007:
#   - set_rls_context_from_staff() is the ONLY context injection function
#   - set_rls_context() was DROPPED in SEC-007 — it no longer exists
#   - set_rls_context_internal() exists for service_role ops lane only
# ==============================================================================

echo "🔒 Checking migration safety (RLS policy protection)..."
echo ""

# Get all staged SQL migration files (exclude deleted files - they show as 'D' in status)
MIGRATION_FILES=$(git diff --cached --name-only --diff-filter=d | grep 'supabase/migrations/.*\.sql$' || true)

if [ -z "$MIGRATION_FILES" ]; then
  echo "✅ No migrations staged"
  exit 0
fi

VIOLATIONS_FOUND=0
WARNINGS_FOUND=0

# ==============================================================================
# Check 1: Block sync_remote_changes.sql files
# These are auto-generated by supabase db pull and often overwrite custom policies
# ==============================================================================
SYNC_FILES=$(echo "$MIGRATION_FILES" | grep -i 'sync_remote_changes' || true)

if [ -n "$SYNC_FILES" ]; then
  echo "❌ CHECK 1 FAILED: Auto-generated sync_remote_changes.sql detected"
  echo ""
  echo "Files flagged:"
  echo "$SYNC_FILES" | sed 's/^/  - /'
  echo ""
  echo "WHY THIS IS DANGEROUS:"
  echo "  • sync_remote_changes.sql is auto-generated by 'supabase db pull'"
  echo "  • These files often overwrite custom RLS policies with simpler versions"
  echo "  • ISSUE-002: This exact pattern caused ADR-015 policy regression"
  echo ""
  echo "REQUIRED ACTIONS:"
  echo "  1. Review the migration content carefully"
  echo "  2. Compare against existing policies in previous migrations"
  echo "  3. Ensure ADR-015 hybrid pattern is preserved (COALESCE with JWT fallback)"
  echo "  4. If verified safe, rename file to describe the actual change"
  echo "  5. Add 'VERIFIED_SAFE_SYNC' comment in migration header"
  echo ""
  echo "BYPASS (use with extreme caution):"
  echo "  git commit --no-verify"
  echo ""
  VIOLATIONS_FOUND=1
fi

# ==============================================================================
# Check 2: Detect RLS policy modifications without review marker
# All DROP POLICY or CREATE POLICY changes must be explicitly reviewed
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Check if file contains policy changes
  HAS_DROP_POLICY=$(git diff --cached "$FILE" | grep -c '^+.*DROP POLICY' || true)
  HAS_CREATE_POLICY=$(git diff --cached "$FILE" | grep -c '^+.*CREATE POLICY' || true)

  if [ "$HAS_DROP_POLICY" -gt 0 ] || [ "$HAS_CREATE_POLICY" -gt 0 ]; then
    # Check for review markers (ADR-015, ADR-034, Wave 2 outbox ADRs, or explicit safe markers)
    HAS_ADR_REFERENCE=$(git diff --cached "$FILE" | grep -c 'ADR-015\|ADR-034\|ADR-054\|ADR-056\|ADR-057\|VERIFIED_SAFE\|RLS_REVIEW_COMPLETE' || true)
    HAS_MIGRATION_HEADER=$(git diff --cached "$FILE" | grep -c '^+-- Migration:\|^+-- Description:\|^+-- Reference:' || true)

    if [ "$HAS_ADR_REFERENCE" -eq 0 ] || [ "$HAS_MIGRATION_HEADER" -lt 2 ]; then
      echo "⚠️  CHECK 2 WARNING: RLS policy changes without review marker"
      echo ""
      echo "File: $FILE"
      echo "  DROP POLICY statements: $HAS_DROP_POLICY"
      echo "  CREATE POLICY statements: $HAS_CREATE_POLICY"
      echo ""
      echo "WHY THIS MATTERS:"
      echo "  • RLS policies are critical for data security and isolation"
      echo "  • Changes must maintain ADR-015 hybrid pattern for connection pooling"
      echo "  • Missing review markers suggest auto-generated or unchecked changes"
      echo ""
      echo "REQUIRED ELEMENTS:"
      echo "  1. Migration header with Description and Reference"
      echo "  2. One of these review markers:"
      echo "     - 'ADR-015' (for hybrid RLS pattern compliance)"
      echo "     - 'ADR-034' (for write-path compatibility)"
      echo "     - 'ADR-054' / 'ADR-056' / 'ADR-057' (for Wave 2 outbox policy changes)"
      echo "     - 'VERIFIED_SAFE' (for verified non-breaking changes)"
      echo "     - 'RLS_REVIEW_COMPLETE' (for manual review completion)"
      echo ""
      echo "EXAMPLE HEADER:"
      echo "  -- Migration: Update player table RLS policies"
      echo "  -- Description: Add ADR-015 hybrid pattern to player_select policy"
      echo "  -- Reference: ADR-015, ISSUE-002"
      echo ""
      WARNINGS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 3: Validate ADR-015 hybrid pattern in new policies
# All casino_id policies should use COALESCE with JWT fallback
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Get newly added CREATE POLICY statements
  NEW_POLICIES=$(git diff --cached "$FILE" | grep '^+.*CREATE POLICY' || true)

  if [ -n "$NEW_POLICIES" ]; then
    # Check if the file contains casino_id checks
    HAS_CASINO_ID_CHECK=$(git diff --cached "$FILE" | grep -c '^+.*casino_id.*=' || true)

    if [ "$HAS_CASINO_ID_CHECK" -gt 0 ]; then
      # Verify hybrid pattern is used
      HAS_HYBRID_PATTERN=$(git diff --cached "$FILE" | grep -c 'COALESCE.*current_setting.*app\.casino_id.*auth\.jwt.*app_metadata.*casino_id' || true)
      HAS_SIMPLE_SETTING=$(git diff --cached "$FILE" | grep -c "current_setting('app\.casino_id')" || true)

      # If using current_setting but NOT using hybrid pattern, flag it
      if [ "$HAS_SIMPLE_SETTING" -gt 0 ] && [ "$HAS_HYBRID_PATTERN" -eq 0 ]; then
        echo "⚠️  CHECK 3 WARNING: RLS policy may lack ADR-015 hybrid pattern"
        echo ""
        echo "File: $FILE"
        echo ""
        echo "DETECTED PATTERN:"
        echo "  • Uses current_setting('app.casino_id') for casino isolation"
        echo "  • Missing COALESCE with JWT fallback (ADR-015 Pattern C)"
        echo ""
        echo "WHY THIS IS RISKY:"
        echo "  • Will fail with Supabase connection pooling (transaction mode)"
        echo "  • SET LOCAL doesn't persist across pooled connections"
        echo "  • Causes RLS bypass or access denial errors"
        echo ""
        echo "ADR-034 POSTURE CHECK:"
        echo "  • Category A tables: session-var-only is CORRECT (RPC-only writes)"
        echo "  • Category B tables: MUST use COALESCE hybrid pattern"
        echo "  • Verify table category in config/rls-category-a-tables.json"
        echo ""
        echo "REQUIRED PATTERN for Category B (ADR-015 Hybrid):"
        echo "  casino_id = COALESCE("
        echo "    NULLIF(current_setting('app.casino_id', true), '')::uuid,"
        echo "    (auth.jwt() -> 'app_metadata' ->> 'casino_id')::uuid"
        echo "  )"
        echo ""
        echo "REFERENCE:"
        echo "  • ADR-015: docs/80-adrs/ADR-015-rls-connection-pooling-strategy.md"
        echo "  • ADR-034: docs/80-adrs/ADR-034-RLS-write-path-compatibility-and-enforcement.md"
        echo ""
        WARNINGS_FOUND=1
      fi
    fi
  fi
done

# ==============================================================================
# Check 3a: Validate ADR-015 hybrid actor_id pattern (staff identity)
# Policies using app.actor_id should include JWT fallback (staff_id)
# NOTE: ADR-024 migrations using set_rls_context_from_staff() are exempt since
#       they derive actor_id authoritatively from the staff table, not JWT.
#       This includes SECURITY DEFINER RPCs and fn_finance_outbox_emit (Wave 2).
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  HAS_ACTOR_ID_CHECK=$(git diff --cached "$FILE" | grep -c "current_setting('app.actor_id'" || true)

  if [ "$HAS_ACTOR_ID_CHECK" -gt 0 ]; then
    # Check if using ADR-024 authoritative context injection (exempt from hybrid check)
    HAS_ADR024_PATTERN=$(git diff --cached "$FILE" | grep -c 'set_rls_context_from_staff' || true)

    if [ "$HAS_ADR024_PATTERN" -gt 0 ]; then
      # ADR-024 pattern: actor_id is derived from staff table, not JWT
      continue
    fi

    HAS_ACTOR_HYBRID=$(git diff --cached "$FILE" | grep -c "COALESCE.*current_setting('app.actor_id'.*auth\.jwt.*app_metadata.*staff_id" || true)

    if [ "$HAS_ACTOR_HYBRID" -eq 0 ]; then
      echo "⚠️  CHECK 3A WARNING: actor_id check lacks ADR-015 hybrid fallback (staff_id)"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "PREFERRED SOLUTION (ADR-024):"
      echo "  PERFORM set_rls_context_from_staff();  -- Derives actor_id from staff table"
      echo ""
      echo "ALTERNATIVE (ADR-015 Hybrid):"
      echo "  id = COALESCE("
      echo "    NULLIF(current_setting('app.actor_id', true), '')::uuid,"
      echo "    (auth.jwt() -> 'app_metadata' ->> 'staff_id')::uuid"
      echo "  )"
      echo ""
      WARNINGS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 3b: Validate ADR-015 hybrid staff_role pattern
# Policies using app.staff_role should include JWT fallback (staff_role)
# NOTE: ADR-024 migrations using set_rls_context_from_staff() are exempt since
#       they derive staff_role from the staff table authoritatively.
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  HAS_STAFF_ROLE_CHECK=$(git diff --cached "$FILE" | grep -c "current_setting('app.staff_role'" || true)

  if [ "$HAS_STAFF_ROLE_CHECK" -gt 0 ]; then
    # Check if using ADR-024 authoritative context injection (exempt from hybrid check)
    HAS_ADR024_PATTERN=$(git diff --cached "$FILE" | grep -c 'set_rls_context_from_staff' || true)

    if [ "$HAS_ADR024_PATTERN" -gt 0 ]; then
      # ADR-024 pattern: staff_role is derived from staff table, not JWT
      continue
    fi

    HAS_ROLE_HYBRID=$(git diff --cached "$FILE" | grep -c "COALESCE.*current_setting('app.staff_role'.*auth\.jwt.*app_metadata.*staff_role" || true)

    if [ "$HAS_ROLE_HYBRID" -eq 0 ]; then
      echo "⚠️  CHECK 3B WARNING: staff_role check lacks ADR-015 hybrid fallback (staff_role claim)"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "PREFERRED SOLUTION (ADR-024):"
      echo "  PERFORM set_rls_context_from_staff();  -- Derives staff_role from staff table"
      echo ""
      echo "ALTERNATIVE (ADR-015 Hybrid):"
      echo "  COALESCE("
      echo "    NULLIF(current_setting('app.staff_role', true), ''),"
      echo "    (auth.jwt() -> 'app_metadata' ->> 'staff_role')"
      echo "  )"
      echo ""
      WARNINGS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 4: Ensure auth.uid() guard on all policies
# All RLS policies must include auth.uid() IS NOT NULL
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Get line numbers of new CREATE POLICY statements
  CREATE_POLICY_LINES=$(git diff --cached "$FILE" | grep -n '^+.*CREATE POLICY' | cut -d: -f1 || true)

  if [ -n "$CREATE_POLICY_LINES" ]; then
    for LINE_NUM in $CREATE_POLICY_LINES; do
      # Extract policy block (next 20 lines after CREATE POLICY)
      POLICY_BLOCK=$(git diff --cached "$FILE" | tail -n +$LINE_NUM | head -n 20)

      # Check if block contains auth.uid() IS NOT NULL
      HAS_AUTH_GUARD=$(echo "$POLICY_BLOCK" | grep -c 'auth\.uid().*IS NOT NULL' || true)

      if [ "$HAS_AUTH_GUARD" -eq 0 ]; then
        # Extract policy name for better error message
        POLICY_NAME=$(echo "$POLICY_BLOCK" | head -n 1 | sed 's/^+.*CREATE POLICY \([^ ]*\).*/\1/')

        echo "⚠️  CHECK 4 WARNING: RLS policy missing auth.uid() guard"
        echo ""
        echo "File: $FILE"
        echo "Policy: $POLICY_NAME"
        echo ""
        echo "WHY THIS IS CRITICAL:"
        echo "  • ALL RLS policies MUST include 'auth.uid() IS NOT NULL'"
        echo "  • Prevents anonymous access to protected data"
        echo "  • Required by ADR-015 security guards"
        echo ""
        echo "REQUIRED PATTERN:"
        echo "  CREATE POLICY policy_name ON table_name"
        echo "    FOR SELECT USING ("
        echo "      auth.uid() IS NOT NULL"
        echo "      AND [other conditions]"
        echo "    );"
        echo ""
        WARNINGS_FOUND=1
      fi
    done
  fi
done

# ==============================================================================
# Check 5: Protect RLS context infrastructure (set_rls_context_from_staff,
#           set_rls_context_internal, JWT triggers)
# Post-SEC-007: set_rls_context() is DROPPED — only _from_staff and _internal remain.
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Check for modifications to set_rls_context_from_staff (ADR-024 — primary)
  HAS_RLS_FROM_STAFF_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*set_rls_context_from_staff' || true)
  HAS_RLS_FROM_STAFF_REPLACE=$(git diff --cached "$FILE" | grep -c '^+.*CREATE OR REPLACE FUNCTION.*set_rls_context_from_staff' || true)

  # Check for modifications to set_rls_context_internal (ADR-024 ops lane)
  HAS_RLS_INTERNAL_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*set_rls_context_internal' || true)

  # Check for resurrection of dropped set_rls_context() (SEC-007)
  HAS_RLS_CONTEXT_RESURRECT=$(git diff --cached "$FILE" | grep -cE '^+.*(CREATE|CREATE OR REPLACE)\s+FUNCTION\s+set_rls_context\s*\(' "$FILE" || true)

  # Check for modifications to JWT claims trigger
  HAS_JWT_TRIGGER_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP TRIGGER.*sync_staff_jwt_claims\|trg_sync_staff_jwt_claims' || true)

  # Check for modifications to JWT claims sync function
  HAS_JWT_FUNC_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*sync_staff_jwt_claims' || true)

  # Check for ADR reference (accepts ADR-015, ADR-024, ADR-030)
  HAS_ADR_REFERENCE=$(git diff --cached "$FILE" | grep -c 'ADR-015\|ADR-024\|ADR-030' || true)

  # Block resurrection of dropped function
  if [ "$HAS_RLS_CONTEXT_RESURRECT" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration recreates set_rls_context() — DROPPED in SEC-007"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS BLOCKED:"
    echo "  • set_rls_context() was intentionally dropped in SEC-007"
    echo "  • It accepted spoofable parameters (actor_id, casino_id, role)"
    echo "  • Use set_rls_context_from_staff() instead (ADR-024)"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  # Protect ADR-024 infrastructure (set_rls_context_from_staff)
  if [ "$HAS_RLS_FROM_STAFF_DROP" -gt 0 ]; then
    # Allow DROP+CREATE when migration contains VERIFIED_SAFE marker and recreates the function
    HAS_VERIFIED_SAFE=$(git diff --cached "$FILE" | grep -c 'VERIFIED_SAFE' || true)
    HAS_RECREATE=$(git diff --cached "$FILE" | grep -c '^+.*CREATE FUNCTION.*set_rls_context_from_staff' || true)

    if [ "$HAS_VERIFIED_SAFE" -gt 0 ] && [ "$HAS_RECREATE" -gt 0 ]; then
      echo "✅ CHECK 5: DROP+CREATE set_rls_context_from_staff() — VERIFIED_SAFE (signature change)"
    else
      echo "❌ CHECK 5 FAILED: Migration drops set_rls_context_from_staff() (ADR-024 critical)"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "WHY THIS IS CRITICAL:"
      echo "  • set_rls_context_from_staff() is the ADR-024 authoritative context injection"
      echo "  • All client-callable RPCs depend on this function"
      echo "  • Dropping breaks RLS enforcement for all operations"
      echo ""
      echo "If this is a DROP+CREATE for signature change, add 'VERIFIED_SAFE' comment"
      echo "above the DROP statement and ensure the function is recreated in the same migration."
      echo ""
      VIOLATIONS_FOUND=1
    fi
  fi

  if [ "$HAS_RLS_FROM_STAFF_REPLACE" -gt 0 ]; then
    if [ "$HAS_ADR_REFERENCE" -eq 0 ]; then
      echo "⚠️  CHECK 5 WARNING: Migration modifies set_rls_context_from_staff() without ADR reference"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "This function is ADR-024 critical infrastructure."
      echo "Add 'ADR-024' reference to migration header to confirm intentional change."
      echo ""
      WARNINGS_FOUND=1
    fi
  fi

  # Protect ADR-024 ops lane (set_rls_context_internal)
  if [ "$HAS_RLS_INTERNAL_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops set_rls_context_internal() (ADR-024 ops lane)"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • set_rls_context_internal() is the ADR-024 ops lane for service_role"
    echo "  • Required for migrations, admin operations, and internal tooling"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  if [ "$HAS_JWT_TRIGGER_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops JWT claims sync trigger"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • trg_sync_staff_jwt_claims is ADR-015 Phase 2 infrastructure"
    echo "  • This trigger syncs staff.casino_id to auth.users.app_metadata"
    echo "  • Required for JWT fallback in hybrid RLS policies (Pattern C)"
    echo ""
    echo "REQUIRED ACTIONS:"
    echo "  1. Verify this is intentional"
    echo "  2. Add 'ADR-015' reference to migration header"
    echo "  3. Ensure JWT claims sync still works after migration"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  if [ "$HAS_JWT_FUNC_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops sync_staff_jwt_claims() function"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • sync_staff_jwt_claims() is ADR-015 Phase 2 infrastructure"
    echo "  • This function syncs staff claims to auth.users.app_metadata"
    echo "  • Used by trigger and application layer (services/casino/crud.ts)"
    echo "  • Required for JWT fallback in hybrid RLS policies (Pattern C)"
    echo ""
    echo "REQUIRED ACTIONS:"
    echo "  1. Verify this is intentional (replacement migration?)"
    echo "  2. Add 'ADR-015' reference to migration header"
    echo "  3. Ensure JWT claims sync still works after migration"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  # Protect Wave 2 outbox emission helper (ADR-054 R3)
  HAS_OUTBOX_EMIT_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*fn_finance_outbox_emit' || true)
  HAS_OUTBOX_EMIT_REPLACE=$(git diff --cached "$FILE" | grep -c '^+.*CREATE OR REPLACE FUNCTION.*fn_finance_outbox_emit' || true)

  if [ "$HAS_OUTBOX_EMIT_DROP" -gt 0 ]; then
    HAS_VERIFIED_SAFE=$(git diff --cached "$FILE" | grep -c 'VERIFIED_SAFE' || true)
    HAS_RECREATE=$(git diff --cached "$FILE" | grep -c '^+.*CREATE.*FUNCTION.*fn_finance_outbox_emit' || true)

    if [ "$HAS_VERIFIED_SAFE" -gt 0 ] && [ "$HAS_RECREATE" -gt 0 ]; then
      echo "✅ CHECK 5: DROP+CREATE fn_finance_outbox_emit() — VERIFIED_SAFE"
    else
      echo "❌ CHECK 5 FAILED: Migration drops fn_finance_outbox_emit() (ADR-054 R3 critical)"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "WHY THIS IS CRITICAL:"
      echo "  • fn_finance_outbox_emit() is the sole authorized outbox insertion path"
      echo "  • All fact-authoring RPCs call it within the same BEGIN…COMMIT (ADR-054 R3)"
      echo "  • Dropping it silently removes the transactional outbox transport substrate"
      echo ""
      echo "If this is a DROP+CREATE for a signature change, add 'VERIFIED_SAFE' comment"
      echo "above the DROP and ensure the function is recreated in the same migration."
      echo ""
      VIOLATIONS_FOUND=1
    fi
  fi

  if [ "$HAS_OUTBOX_EMIT_REPLACE" -gt 0 ]; then
    HAS_ADR054_REFERENCE=$(git diff --cached "$FILE" | grep -c 'ADR-054\|ADR-057' || true)
    if [ "$HAS_ADR054_REFERENCE" -eq 0 ]; then
      echo "⚠️  CHECK 5 WARNING: Migration modifies fn_finance_outbox_emit() without ADR-054/ADR-057 reference"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "fn_finance_outbox_emit() is Wave 2 outbox transport infrastructure."
      echo "Add 'ADR-054' or 'ADR-057' reference to confirm intentional change."
      echo ""
      WARNINGS_FOUND=1
    fi
  fi

  # Protect Wave 2 relay RPCs (ADR-056)
  HAS_CLAIM_BATCH_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*rpc_claim_outbox_batch' || true)
  HAS_COMMIT_RECEIPT_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*rpc_commit_consumer_receipt' || true)
  HAS_ACKNOWLEDGE_DROP=$(git diff --cached "$FILE" | grep -c '^+.*DROP FUNCTION.*rpc_acknowledge_outbox_delivery' || true)

  if [ "$HAS_CLAIM_BATCH_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops rpc_claim_outbox_batch() (relay infrastructure)"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • rpc_claim_outbox_batch() is the relay worker's only read path for the outbox"
    echo "  • Uses FOR UPDATE SKIP LOCKED for concurrent relay safety (ADR-056)"
    echo "  • Dropping it breaks the outbox relay worker immediately"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  if [ "$HAS_COMMIT_RECEIPT_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops rpc_commit_consumer_receipt() (relay infrastructure)"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • rpc_commit_consumer_receipt() is the relay worker's idempotency commit path"
    echo "  • Writes to processed_messages within the same transaction as projection updates"
    echo "  • Dropping it breaks consumer idempotency enforcement (ADR-054 D5)"
    echo ""
    VIOLATIONS_FOUND=1
  fi

  if [ "$HAS_ACKNOWLEDGE_DROP" -gt 0 ]; then
    echo "❌ CHECK 5 FAILED: Migration drops rpc_acknowledge_outbox_delivery() (relay infrastructure)"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS CRITICAL:"
    echo "  • rpc_acknowledge_outbox_delivery() is the authorized terminal delivery-state write path"
    echo "  • Sole function that may set processed_at or last_error on finance_outbox rows"
    echo "  • Dropping it eliminates the governed acknowledgement path (ADR-054 R3, ADR-056)"
    echo "  • The relay worker will have no write path for delivery acknowledgement"
    echo ""
    VIOLATIONS_FOUND=1
  fi
done

# ==============================================================================
# Check 5b: Protect outbox DDL tables from accidental DROP TABLE
# finance_outbox and processed_messages are Wave 2 transport substrate.
# Dropping them destroys the entire outbox pipeline.
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  if [ ! -f "$FILE" ]; then
    continue
  fi

  HAS_DROP_OUTBOX=$(git diff --cached "$FILE" | grep -ciE '^+\s*DROP TABLE.*(finance_outbox|IF EXISTS.*finance_outbox)' || true)
  HAS_DROP_PROCESSED=$(git diff --cached "$FILE" | grep -ciE '^+\s*DROP TABLE.*(processed_messages|IF EXISTS.*processed_messages)' || true)

  if [ "$HAS_DROP_OUTBOX" -gt 0 ]; then
    HAS_VERIFIED_SAFE=$(git diff --cached "$FILE" | grep -c 'VERIFIED_SAFE' || true)
    if [ "$HAS_VERIFIED_SAFE" -eq 0 ]; then
      echo "❌ CHECK 5B FAILED: Migration drops finance_outbox table"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "WHY THIS IS CRITICAL:"
      echo "  • finance_outbox is the Wave 2 transactional outbox DDL"
      echo "  • Dropping it destroys all un-relayed outbox rows and breaks the relay worker"
      echo "  • All producer RPCs (rpc_create_financial_txn, rpc_create_financial_adjustment,"
      echo "    rpc_record_grind_observation) depend on this table"
      echo ""
      echo "If this DROP is intentional (schema replacement), add 'VERIFIED_SAFE' comment"
      echo "and ensure the table is recreated with the Wave 2 ADR-054 schema in the same migration."
      echo ""
      VIOLATIONS_FOUND=1
    fi
  fi

  if [ "$HAS_DROP_PROCESSED" -gt 0 ]; then
    HAS_VERIFIED_SAFE=$(git diff --cached "$FILE" | grep -c 'VERIFIED_SAFE' || true)
    if [ "$HAS_VERIFIED_SAFE" -eq 0 ]; then
      echo "❌ CHECK 5B FAILED: Migration drops processed_messages table"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "WHY THIS IS CRITICAL:"
      echo "  • processed_messages is the consumer idempotency store"
      echo "  • Dropping it loses all delivery receipts — consumers will replay all events"
      echo "  • Breaks rpc_commit_consumer_receipt and I3 idempotency invariant"
      echo ""
      VIOLATIONS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 6a: Detect dangerous bulk REVOKE patterns
# REVOKE ALL ON ALL FUNCTIONS or REVOKE ... FROM authenticated without
# corresponding GRANT risks silently breaking authenticated access.
# Reference: GAP-AUTHENTICATED-ROLE-GRANT-BLIND-SPOT (P1 2026-04-08)
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  HAS_BULK_REVOKE=$(git diff --cached "$FILE" | grep -c '^+.*REVOKE ALL ON ALL FUNCTIONS' || true)
  HAS_REVOKE_AUTHENTICATED=$(git diff --cached "$FILE" | grep -c '^+.*REVOKE.*FROM authenticated' || true)

  if [ "$HAS_BULK_REVOKE" -gt 0 ]; then
    echo "⚠️  CHECK 6A WARNING: Bulk REVOKE ALL ON ALL FUNCTIONS detected"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "WHY THIS IS DANGEROUS:"
    echo "  • Strips EXECUTE grants from ALL functions, including authenticated role"
    echo "  • Any function not explicitly re-granted will silently break"
    echo "  • This pattern caused the P1 incident (2026-04-08)"
    echo ""
    echo "REQUIRED ACTIONS:"
    echo "  1. Enumerate every rpc_* function and re-grant explicitly"
    echo "  2. Run SEC-010 gate (10_authenticated_grant_audit.sql) locally"
    echo "  3. Add 'GRANT_AUDIT_VERIFIED' comment to migration header"
    echo ""
    WARNINGS_FOUND=1
  fi

  if [ "$HAS_REVOKE_AUTHENTICATED" -gt 0 ]; then
    HAS_GRANT_AUTHENTICATED=$(git diff --cached "$FILE" | grep -c '^+.*GRANT.*TO authenticated' || true)
    if [ "$HAS_GRANT_AUTHENTICATED" -eq 0 ]; then
      echo "⚠️  CHECK 6A WARNING: REVOKE FROM authenticated without corresponding GRANT"
      echo ""
      echo "File: $FILE"
      echo ""
      echo "WHY THIS IS DANGEROUS:"
      echo "  • Removes authenticated EXECUTE without re-granting"
      echo "  • Verify this is intentional (internal-only function?)"
      echo "  • If the function is client-callable, add GRANT EXECUTE TO authenticated"
      echo ""
      WARNINGS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 6: Detect legacy exec_sql() usage in migrations
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Check for new exec_sql function creation (deprecated pattern)
  HAS_EXEC_SQL=$(git diff --cached "$FILE" | grep -c '^+.*CREATE.*FUNCTION.*exec_sql' || true)

  if [ "$HAS_EXEC_SQL" -gt 0 ]; then
    echo "⚠️  CHECK 6 WARNING: Migration creates exec_sql() function (deprecated)"
    echo ""
    echo "File: $FILE"
    echo ""
    echo "The exec_sql() RPC is DEPRECATED per ADR-015."
    echo "This pattern fails with Supabase connection pooling."
    echo ""
    echo "Use set_rls_context() instead for context injection."
    echo ""
    echo "Reference: ADR-015 (RLS Connection Pooling Strategy)"
    echo ""
    WARNINGS_FOUND=1
  fi
done

# ==============================================================================
# Summary and Exit
# ==============================================================================
echo ""

if [ "$VIOLATIONS_FOUND" -gt 0 ]; then
  echo "❌ COMMIT BLOCKED: Critical migration safety violations detected"
  echo ""
  echo "Your commit contains risky migration patterns that could cause data security"
  echo "or access control regressions (like ISSUE-002)."
  echo ""
  echo "NEXT STEPS:"
  echo "  1. Review the violations above carefully"
  echo "  2. Fix the issues or add required review markers"
  echo "  3. If you've verified the changes are safe:"
  echo "     - Add proper migration headers and ADR references"
  echo "     - Ensure ADR-015 hybrid pattern is preserved"
  echo "     - Add VERIFIED_SAFE comment to migration"
  echo ""
  echo "BYPASS (dangerous, use only if absolutely certain):"
  echo "  git commit --no-verify"
  echo ""
  exit 1
fi

if [ "$WARNINGS_FOUND" -gt 0 ]; then
  echo "⚠️  WARNINGS: Potential migration issues detected (review recommended)"
  echo ""
  echo "Your commit has passed blocking checks but contains patterns that warrant"
  echo "manual review before deployment."
  echo ""
  echo "RECOMMENDED ACTIONS:"
  echo "  1. Review warnings above"
  echo "  2. Verify ADR-015 compliance for RLS policies"
  echo "  3. Add migration header with ADR references"
  echo "  4. Test with connection pooling enabled"
  echo ""
  echo "To proceed with commit:"
  echo "  - Commit will continue (warnings don't block)"
  echo "  - Consider fixing warnings before merge to main"
  echo ""
  echo "BYPASS WARNINGS:"
  echo "  git commit --no-verify"
  echo ""
  # Warnings don't block commit, just inform
  exit 0
fi

echo "✅ Migration safety checks passed"
exit 0
