#!/bin/sh
# ==============================================================================
# Migration Safety Check - RLS Policy Protection
# ==============================================================================
# Version: 1.0.0
# Date: 2025-12-09
# References:
#   - ISSUE-002: sync_remote_changes.sql overwrote ADR-015 hybrid RLS policies
#   - ADR-015: RLS Connection Pooling Strategy (Hybrid Pattern C)
#
# Prevents accidental RLS policy regressions from:
#   1. Supabase CLI auto-generated sync_remote_changes.sql files
#   2. Migrations that modify RLS policies without explicit review markers
#   3. Policy changes that may lack ADR-015 hybrid fallback pattern
# ==============================================================================

echo "🔒 Checking migration safety (RLS policy protection)..."
echo ""

# Get all staged SQL migration files
MIGRATION_FILES=$(git diff --cached --name-only | grep 'supabase/migrations/.*\.sql$' || true)

if [ -z "$MIGRATION_FILES" ]; then
  echo "✅ No migrations staged"
  exit 0
fi

VIOLATIONS_FOUND=0
WARNINGS_FOUND=0

# ==============================================================================
# Check 1: Block sync_remote_changes.sql files
# These are auto-generated by supabase db pull and often overwrite custom policies
# ==============================================================================
SYNC_FILES=$(echo "$MIGRATION_FILES" | grep -i 'sync_remote_changes' || true)

if [ -n "$SYNC_FILES" ]; then
  echo "❌ CHECK 1 FAILED: Auto-generated sync_remote_changes.sql detected"
  echo ""
  echo "Files flagged:"
  echo "$SYNC_FILES" | sed 's/^/  - /'
  echo ""
  echo "WHY THIS IS DANGEROUS:"
  echo "  • sync_remote_changes.sql is auto-generated by 'supabase db pull'"
  echo "  • These files often overwrite custom RLS policies with simpler versions"
  echo "  • ISSUE-002: This exact pattern caused ADR-015 policy regression"
  echo ""
  echo "REQUIRED ACTIONS:"
  echo "  1. Review the migration content carefully"
  echo "  2. Compare against existing policies in previous migrations"
  echo "  3. Ensure ADR-015 hybrid pattern is preserved (COALESCE with JWT fallback)"
  echo "  4. If verified safe, rename file to describe the actual change"
  echo "  5. Add 'VERIFIED_SAFE_SYNC' comment in migration header"
  echo ""
  echo "BYPASS (use with extreme caution):"
  echo "  git commit --no-verify"
  echo ""
  VIOLATIONS_FOUND=1
fi

# ==============================================================================
# Check 2: Detect RLS policy modifications without review marker
# All DROP POLICY or CREATE POLICY changes must be explicitly reviewed
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Check if file contains policy changes
  HAS_DROP_POLICY=$(git diff --cached "$FILE" | grep -c '^+.*DROP POLICY' || true)
  HAS_CREATE_POLICY=$(git diff --cached "$FILE" | grep -c '^+.*CREATE POLICY' || true)

  if [ "$HAS_DROP_POLICY" -gt 0 ] || [ "$HAS_CREATE_POLICY" -gt 0 ]; then
    # Check for review markers
    HAS_ADR_REFERENCE=$(git diff --cached "$FILE" | grep -c 'ADR-015\|VERIFIED_SAFE\|RLS_REVIEW_COMPLETE' || true)
    HAS_MIGRATION_HEADER=$(git diff --cached "$FILE" | grep -c '^+-- Migration:\|^+-- Description:\|^+-- Reference:' || true)

    if [ "$HAS_ADR_REFERENCE" -eq 0 ] || [ "$HAS_MIGRATION_HEADER" -lt 2 ]; then
      echo "⚠️  CHECK 2 WARNING: RLS policy changes without review marker"
      echo ""
      echo "File: $FILE"
      echo "  DROP POLICY statements: $HAS_DROP_POLICY"
      echo "  CREATE POLICY statements: $HAS_CREATE_POLICY"
      echo ""
      echo "WHY THIS MATTERS:"
      echo "  • RLS policies are critical for data security and isolation"
      echo "  • Changes must maintain ADR-015 hybrid pattern for connection pooling"
      echo "  • Missing review markers suggest auto-generated or unchecked changes"
      echo ""
      echo "REQUIRED ELEMENTS:"
      echo "  1. Migration header with Description and Reference"
      echo "  2. One of these review markers:"
      echo "     - 'ADR-015' (for hybrid RLS pattern compliance)"
      echo "     - 'VERIFIED_SAFE' (for verified non-breaking changes)"
      echo "     - 'RLS_REVIEW_COMPLETE' (for manual review completion)"
      echo ""
      echo "EXAMPLE HEADER:"
      echo "  -- Migration: Update player table RLS policies"
      echo "  -- Description: Add ADR-015 hybrid pattern to player_select policy"
      echo "  -- Reference: ADR-015, ISSUE-002"
      echo ""
      WARNINGS_FOUND=1
    fi
  fi
done

# ==============================================================================
# Check 3: Validate ADR-015 hybrid pattern in new policies
# All casino_id policies should use COALESCE with JWT fallback
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Get newly added CREATE POLICY statements
  NEW_POLICIES=$(git diff --cached "$FILE" | grep '^+.*CREATE POLICY' || true)

  if [ -n "$NEW_POLICIES" ]; then
    # Check if the file contains casino_id checks
    HAS_CASINO_ID_CHECK=$(git diff --cached "$FILE" | grep -c '^+.*casino_id.*=' || true)

    if [ "$HAS_CASINO_ID_CHECK" -gt 0 ]; then
      # Verify hybrid pattern is used
      HAS_HYBRID_PATTERN=$(git diff --cached "$FILE" | grep -c 'COALESCE.*current_setting.*app\.casino_id.*auth\.jwt.*app_metadata.*casino_id' || true)
      HAS_SIMPLE_SETTING=$(git diff --cached "$FILE" | grep -c "current_setting('app\.casino_id')" || true)

      # If using current_setting but NOT using hybrid pattern, flag it
      if [ "$HAS_SIMPLE_SETTING" -gt 0 ] && [ "$HAS_HYBRID_PATTERN" -eq 0 ]; then
        echo "⚠️  CHECK 3 WARNING: RLS policy may lack ADR-015 hybrid pattern"
        echo ""
        echo "File: $FILE"
        echo ""
        echo "DETECTED PATTERN:"
        echo "  • Uses current_setting('app.casino_id') for casino isolation"
        echo "  • Missing COALESCE with JWT fallback (ADR-015 Pattern C)"
        echo ""
        echo "WHY THIS IS RISKY:"
        echo "  • Will fail with Supabase connection pooling (transaction mode)"
        echo "  • SET LOCAL doesn't persist across pooled connections"
        echo "  • Causes RLS bypass or access denial errors"
        echo ""
        echo "REQUIRED PATTERN (ADR-015 Hybrid):"
        echo "  casino_id = COALESCE("
        echo "    NULLIF(current_setting('app.casino_id', true), '')::uuid,"
        echo "    (auth.jwt() -> 'app_metadata' ->> 'casino_id')::uuid"
        echo "  )"
        echo ""
        echo "REFERENCE:"
        echo "  • ADR-015: docs/80-adrs/ADR-015-rls-connection-pooling-strategy.md"
        echo "  • Example: supabase/migrations/20251209183401_adr015_hybrid_rls_policies.sql"
        echo ""
        WARNINGS_FOUND=1
      fi
    fi
  fi
done

# ==============================================================================
# Check 4: Ensure auth.uid() guard on all policies
# All RLS policies must include auth.uid() IS NOT NULL
# ==============================================================================
for FILE in $MIGRATION_FILES; do
  # Get line numbers of new CREATE POLICY statements
  CREATE_POLICY_LINES=$(git diff --cached "$FILE" | grep -n '^+.*CREATE POLICY' | cut -d: -f1 || true)

  if [ -n "$CREATE_POLICY_LINES" ]; then
    for LINE_NUM in $CREATE_POLICY_LINES; do
      # Extract policy block (next 20 lines after CREATE POLICY)
      POLICY_BLOCK=$(git diff --cached "$FILE" | tail -n +$LINE_NUM | head -n 20)

      # Check if block contains auth.uid() IS NOT NULL
      HAS_AUTH_GUARD=$(echo "$POLICY_BLOCK" | grep -c 'auth\.uid().*IS NOT NULL' || true)

      if [ "$HAS_AUTH_GUARD" -eq 0 ]; then
        # Extract policy name for better error message
        POLICY_NAME=$(echo "$POLICY_BLOCK" | head -n 1 | sed 's/^+.*CREATE POLICY \([^ ]*\).*/\1/')

        echo "⚠️  CHECK 4 WARNING: RLS policy missing auth.uid() guard"
        echo ""
        echo "File: $FILE"
        echo "Policy: $POLICY_NAME"
        echo ""
        echo "WHY THIS IS CRITICAL:"
        echo "  • ALL RLS policies MUST include 'auth.uid() IS NOT NULL'"
        echo "  • Prevents anonymous access to protected data"
        echo "  • Required by ADR-015 security guards"
        echo ""
        echo "REQUIRED PATTERN:"
        echo "  CREATE POLICY policy_name ON table_name"
        echo "    FOR SELECT USING ("
        echo "      auth.uid() IS NOT NULL"
        echo "      AND [other conditions]"
        echo "    );"
        echo ""
        WARNINGS_FOUND=1
      fi
    done
  fi
done

# ==============================================================================
# Summary and Exit
# ==============================================================================
echo ""

if [ "$VIOLATIONS_FOUND" -gt 0 ]; then
  echo "❌ COMMIT BLOCKED: Critical migration safety violations detected"
  echo ""
  echo "Your commit contains risky migration patterns that could cause data security"
  echo "or access control regressions (like ISSUE-002)."
  echo ""
  echo "NEXT STEPS:"
  echo "  1. Review the violations above carefully"
  echo "  2. Fix the issues or add required review markers"
  echo "  3. If you've verified the changes are safe:"
  echo "     - Add proper migration headers and ADR references"
  echo "     - Ensure ADR-015 hybrid pattern is preserved"
  echo "     - Add VERIFIED_SAFE comment to migration"
  echo ""
  echo "BYPASS (dangerous, use only if absolutely certain):"
  echo "  git commit --no-verify"
  echo ""
  exit 1
fi

if [ "$WARNINGS_FOUND" -gt 0 ]; then
  echo "⚠️  WARNINGS: Potential migration issues detected (review recommended)"
  echo ""
  echo "Your commit has passed blocking checks but contains patterns that warrant"
  echo "manual review before deployment."
  echo ""
  echo "RECOMMENDED ACTIONS:"
  echo "  1. Review warnings above"
  echo "  2. Verify ADR-015 compliance for RLS policies"
  echo "  3. Add migration header with ADR references"
  echo "  4. Test with connection pooling enabled"
  echo ""
  echo "To proceed with commit:"
  echo "  - Commit will continue (warnings don't block)"
  echo "  - Consider fixing warnings before merge to main"
  echo ""
  echo "BYPASS WARNINGS:"
  echo "  git commit --no-verify"
  echo ""
  # Warnings don't block commit, just inform
  exit 0
fi

echo "✅ Migration safety checks passed"
exit 0
